import "./camel-case.microdash";
import "./capitalize.microdash";
import "./kebab-case.microdash";
import "./pad-end.microdash";
import "./pad-start.microdash";
import "./pad.microdash";
import "./to-lower.microdash";
import "./upper-first.microdash";
import "./words.microdash";
